name: playground_for_dart
description: Simple examples that help you get started with Appwrite + Dart (=❤️).
# version: 1.0.0
#homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_appwrite: ^2.0.0

dependency_overrides: 
  dart_appwrite:
    # git:
      # url: https://github.com/appwrite/sdk-for-dart
      # ref: db-alpha
    path: /home/dlohani/Documents/projects/appwrite/appwrite_src/app/sdks/server-dart

dev_dependencies:
  pedantic: ^1.9.0
